site_dir: site
site_name: JL's Personal
theme:
  name: material
  palette:
    # light mode
  - scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
    primary: indigo
    accent: cyan

    # dark mode
  - scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
    primary: indigo
    accent: cyan

  features:
    - content.code.copy
    - search.suggest
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - toc.integrate

  highlight_theme: monokai
plugins:
  - include-markdown
  - search
  - tags
extra_css:
  - stylesheets/overrides.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
