site_name: JL's Personal
theme:
  name: material
  palette:
    # light mode
  - scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
    primary: light blue
    accent: orange

    # dark mode
  - scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
    primary: light blue
    accent: orange

  features:
    - content.code.copy
  highlight_theme: monokai
plugins:
  - include-markdown
extra_css:
  - stylesheets/overrides.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
